@startuml

left to right direction
skinparam classAttributeIconSize 0

'Classes declaration
class Cart{
   -items[] : CartItem
   +Cart(cartItems: CartItem[])
   +<get>items():CartItem[]
   +<get>total():float
   +add(items: CartItem[])
   +count(distinct: bool): int
}

class CartItem{
   +CartItem(articleId: int, name: string, quantity: int, price: float)
   +<get,set>quantity():int
   +<get>name():string
   +<get>price():float
}

class EmptyCartException{}
class UpdateCartException{}
class CartException{}
class CartItemException{}
class InvalidArticleIdException{}
class InvalidQuantityException{}
class InvalidPriceException{}

'Relations
Cart o-- CartItem
Cart --> EmptyCartException : throws
Cart --> UpdateCartException : throws
CartItem --> InvalidArticleIdException : throws
CartItem --> InvalidQuantityException : throws
CartItem --> InvalidPriceException : throws

'Exception inheritance
InvalidArticleIdException -|> CartItemException
InvalidPriceException -|> CartItemException
InvalidQuantityException -|> CartItemException
EmptyCartException -|> CartException
UpdateCartException -|> CartException

@enduml