@startuml
class "CartItem" {
  - articleId: int
  - name: string
  - quantity: int
  - price: double
  + getArticleId(): int 
  + getName(): string
  + getQuantity(): int
  + setQuantity(int: value): void
  + getPrice(): double
  + setPrice(double: value): void
  + getTotal(): double
}

exception "Error" {
}

exception "CartItemException" extends Error {
}

exception "InvalidArticleIdException" extends CartItemException {
}

exception "InvalidQuantityException" extends CartItemException {
}

exception "InvalidPriceException" extends CartItemException {
}

CartItem ..> InvalidArticleIdException : "throws"
CartItem ..> InvalidQuantityException : "throws"
CartItem ..> InvalidPriceException : "throws"



@enduml